# Generated by Django 6.0.1 on 2026-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joeflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('failed', 'failed'), ('succeeded', 'succeeded'), ('scheduled', 'scheduled'), ('canceled', 'canceled')], db_index=True, default='created', editable=False, max_length=50),
        ),
    ]
