# Generated by Django 6.0.1 on 2026-01-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigneeWorkflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simpleworkflowstate',),
        ),
    ]
